validations:
  digit:
    length_6: 6
    length_50: 50
gravatar:
  size: 80
  size_change: 50
per_page: 15
password_reset_expired: 2
content:
  length_140: 140
image:
  size_1mb: 1
  resize: [400,400]
  format: ["image/png", "image/jpg", "image/jpeg"]
